// AUTO-GENERATED by scripts/generate_capability_artifacts.py
// DO NOT EDIT MANUALLY. Edit apps/shared/data/unified-apis.json instead.

import * as z from "zod";

export interface CapabilityDef {
  name: string;
  description: string;
  inputSchema: Record<string, z.ZodType>;
}

export const CAPABILITIES: CapabilityDef[] = [
  {
    name: "search",
    description: "Search the web with SERP, AI synthesis, or both. Cost: serp 1 credit, ai 2 credits, deep 3 credits.",
    inputSchema: {
      query: z.string().describe("The search query."),
      num_results: z.number().optional().default(10).describe("Maximum number of organic results (serp and deep modes)."),
      country: z.string().optional().default("us").describe("ISO country code of the Google results (serp and deep modes)."),
      freshness: z.enum(["any", "day", "week", "month"]).optional().default("any").describe("Only sources from this window, in every mode."),
      mode: z.enum(["serp", "ai", "deep"]).optional().describe("Mode: serp (Raw Google SERP results), ai (AI-synthesized answers with citations), deep (SERP + AI synthesis combined)."),
    },
  },
  {
    name: "scrape",
    description: "Extract content from any URL as Markdown or HTML. Cost: fast 1 credit, standard 2 credits, thorough 5 credits.",
    inputSchema: {
      url: z.string().describe("URL to scrape."),
      output: z.enum(["markdown", "html", "raw_html"]).optional().default("markdown").describe("Content format."),
      wait_for: z.string().optional().describe("CSS selector to wait for (standard and thorough modes)."),
      timeout: z.number().optional().default(30).describe("Seconds the page may take to load (up to 55)."),
      mode: z.enum(["fast", "standard", "thorough"]).optional().describe("Mode: fast (Raw HTTP, no JS. <1s), standard (Full JS rendering. 2-5s), thorough (Anti-bot proxies + JS rendering. 10-30s)."),
    },
  },
  {
    name: "profiles",
    description: "Find and enrich professional profiles. Cost: 3 credits.",
    inputSchema: {
      linkedin_url: z.string().optional().describe("LinkedIn profile URL."),
      first_name: z.string().optional().describe("First name."),
      last_name: z.string().optional().describe("Last name."),
      company: z.string().optional().describe("Company name."),
      include_image: z.boolean().optional().default(true).describe("Fetch profile image."),
    },
  },
  {
    name: "emails",
    description: "Find professional email addresses. Cost: 2 credits.",
    inputSchema: {
      first_name: z.string().describe("First name."),
      last_name: z.string().describe("Last name."),
      domain: z.string().describe("Company domain."),
      company: z.string().optional().describe("Company name (optional)."),
    },
  },
  {
    name: "images",
    description: "Generate images from text prompts. Cost: 3 credits.",
    inputSchema: {
      prompt: z.string().describe("Image description."),
      aspect_ratio: z.enum(["1:1", "16:9", "9:16"]).optional().default("1:1").describe("Aspect ratio."),
    },
  },
  {
    name: "tts",
    description: "Convert text to speech audio. Cost: 2 credits.",
    inputSchema: {
      text: z.string().describe("Text to convert (max 2000 chars)."),
      voice_model: z.string().optional().describe("Deepgram voice model ID."),
      provider: z.enum(["auto", "deepgram", "elevenlabs"]).optional().default("auto").describe("TTS provider."),
    },
  },
  {
    name: "stt",
    description: "Transcribe audio to text with timestamps. Cost: 2 credits.",
    inputSchema: {
      audio_url: z.string().optional().describe("URL to audio file."),
      audio_base64: z.string().optional().describe("Base64-encoded audio."),
      language: z.string().optional().default("en").describe("Language code."),
    },
  },
  {
    name: "sound-generate",
    description: "Generate sound effects and short music tracks from text prompts (NOT speech: use tts for spoken voice). Cost: 4 credits.",
    inputSchema: {
      prompt: z.string().describe("Description of the sound effect or music to generate. NOT for speech (use tts for spoken voice)."),
      duration_seconds: z.number().optional().describe("Length of generated audio in seconds (0.5 to 22). Leave unset to let the model auto-decide based on the prompt."),
      prompt_influence: z.number().optional().default(0.3).describe("How strictly to follow the prompt (0.0 = creative, 1.0 = literal). Default 0.3."),
      output_format: z.enum(["mp3_44100_128", "mp3_44100_192", "pcm_44100"]).optional().default("mp3_44100_128").describe("Audio format and quality."),
    },
  },
  {
    name: "sms",
    description: "Send SMS or WhatsApp messages. Default channel is SMS (reliable delivery). WhatsApp requires recipient opt-in: they must have messaged your Business number within 24 hours. Cost: 1 credit.",
    inputSchema: {
      to: z.string().describe("Phone number (E.164)."),
      message: z.string().describe("Message text."),
      channel: z.enum(["auto", "sms", "whatsapp"]).optional().default("auto").describe("Delivery channel. Auto sends via SMS. WhatsApp requires opt-in: recipient must have messaged your Business number in the last 24 hours, otherwise the message is silently dropped by Meta."),
    },
  },
  {
    name: "documents",
    description: "Extract structured data from URLs or content. Cost: 3 credits.",
    inputSchema: {
      url: z.string().optional().describe("URL to scrape and extract from."),
      content: z.string().optional().describe("Pre-scraped text content."),
      extraction_prompt: z.string().describe("What to extract (required unless schema is provided)."),
      schema: z.record(z.string(), z.unknown()).optional().describe("JSON schema for extraction."),
    },
  },
  {
    name: "companies",
    description: "Enrich company data by domain. Cost: 3 credits.",
    inputSchema: {
      domain: z.string().describe("Company domain."),
      company_name: z.string().optional().describe("Optional name hint."),
    },
  },
  {
    name: "email-verify",
    description: "Check if an email is deliverable, catch-all, or disposable. Cost: 1 credit.",
    inputSchema: {
      email: z.string().describe("Email to verify."),
    },
  },
  {
    name: "transcribe",
    description: "Transcribe audio with speaker diarization and timestamps. Cost: 3 credits.",
    inputSchema: {
      audio_url: z.string().describe("URL to audio/video file."),
      language: z.string().optional().default("en").describe("Language code."),
      speaker_labels: z.boolean().optional().default(true).describe("Enable speaker diarization."),
    },
  },
  {
    name: "invoice-parse",
    description: "Extract structured data from invoices and receipts. Cost: 3 credits.",
    inputSchema: {
      document_url: z.string().describe("URL to invoice PDF/image."),
    },
  },
  {
    name: "subtitle",
    description: "Generate SRT/VTT subtitles from audio or video. Cost: 2 credits.",
    inputSchema: {
      audio_url: z.string().describe("URL to audio/video."),
      language: z.string().optional().default("en").describe("Language code."),
      format: z.enum(["srt", "vtt"]).optional().default("srt").describe("Subtitle format."),
    },
  },
  {
    name: "file-convert",
    description: "Convert documents, web pages, spreadsheets and images between formats. Cost: 2 credits.",
    inputSchema: {
      file_url: z.string().describe("URL of the file to convert (for source_format web, the page itself)."),
      source_format: z.string().describe("Format of the file: pdf, docx, pptx, xlsx, csv, html, web (a page, from its HTML without JavaScript), txt, epub, svg, png, jpg, webp, gif, bmp, tiff or heic."),
      target_format: z.string().optional().default("pdf").describe("Format to convert to. The conversion table's pairs convert in-house; other pairs go to ConvertAPI."),
    },
  },
  {
    name: "bg-remove",
    description: "Remove background from any image. Returns transparent PNG. Cost: 2 credits.",
    inputSchema: {
      image_url: z.string().describe("URL to image."),
      size: z.enum(["auto", "small", "hd"]).optional().default("auto").describe("Output resolution."),
    },
  },
  {
    name: "screenshot",
    description: "Capture a rendered screenshot of any webpage. Cost: 1 credit.",
    inputSchema: {
      url: z.string().describe("URL to capture."),
      width: z.number().optional().default(1280).describe("Viewport width."),
      height: z.number().optional().default(720).describe("Viewport height."),
      format: z.enum(["png", "jpg", "webp"]).optional().default("png").describe("Output format."),
      full_page: z.boolean().optional().default(false).describe("Capture full scrollable page."),
    },
  },
  {
    name: "code-execute",
    description: "Execute code in a secure sandbox with pre-configured environments. Cost: 2 credits.",
    inputSchema: {
      code: z.string().describe("The code to execute."),
      language: z.enum(["python", "javascript", "shell"]).optional().default("python").describe("Programming language."),
      timeout: z.number().optional().default(30).describe("Max execution time (1-300s)."),
      template: z.enum(["default", "data-science", "web-dev", "video"]).optional().default("default").describe("Pre-configured environment."),
    },
  },
  {
    name: "site-intel",
    description: "Get comprehensive domain intelligence: WHOIS, DNS, SSL, tech stack, email security, hosting. Cost: overview 2 credits, whois 1 credit, dns 1 credit, tech-stack 2 credits, security 2 credits, subdomains 2 credits.",
    inputSchema: {
      domain: z.string().describe("Domain to analyze (e.g. stripe.com)."),
      mode: z.enum(["overview", "whois", "dns", "tech-stack", "security", "subdomains"]).optional().default("overview").describe("Intelligence depth."),
    },
  },
  {
    name: "research",
    description: "Multi-step deep research: search, scrape, enrich entities, and synthesize into a cited report. Cost: standard 10 credits, deep 20 credits, comprehensive 35 credits.",
    inputSchema: {
      query: z.string().describe("The research question or objective."),
      depth: z.enum(["standard", "deep", "comprehensive"]).optional().default("standard").describe("Research depth."),
      enrich_entities: z.boolean().optional().default(true).describe("Enrich detected people and companies with profile and firmographic data."),
      include_analysis: z.boolean().optional().default(false).describe("Generate computational analysis with charts."),
      synthesis: z.boolean().optional().default(true).describe("Generate a synthesized report. Set false for raw mode (sources + entities only)."),
      source_types: z.string().optional().default("web").describe("Comma-separated source types: web, news, academic."),
      max_sources: z.number().optional().default(15).describe("Maximum number of sources to collect."),
      freshness: z.enum(["any", "day", "week", "month"]).optional().default("any").describe("Time filter for search results."),
    },
  },
  {
    name: "video-info",
    description: "Extract video metadata, available formats, and thumbnail from any URL. Cost: 1 credit.",
    inputSchema: {
      url: z.string().describe("URL of the video or post containing a video."),
    },
  },
  {
    name: "video-download",
    description: "Download video from any URL and return a temporary download link. Cost: video 3 credits, audio 2 credits.",
    inputSchema: {
      url: z.string().describe("URL of the video or post containing a video."),
      quality: z.enum(["360", "480", "720", "1080", "best"]).optional().default("720").describe("Desired video quality (best available up to this resolution)."),
      format: z.enum(["mp4", "mp3", "m4a"]).optional().default("mp4").describe("Output format."),
    },
  },
  {
    name: "domains",
    description: "Find domain names and the extensions that fit a business. Cost: suggest-names 5 credits, suggest-extensions 3 credits, search-extensions 2 credits, check-availability 1 credit, pricing 1 credit, tlds 1 credit.",
    inputSchema: {
      mode: z.enum(["suggest-names", "suggest-extensions", "search-extensions", "check-availability", "pricing", "tlds"]).optional().default("suggest-names").describe("Which domain capability to run."),
      company_name: z.string().optional().describe("The business name (suggest-extensions), or for suggest-names a natural-language brief: any ordering or limit it states (for example \"shortest\" or \"renewal under $15\") is read and applied beneath your explicit search_options."),
      description: z.string().optional().describe("What the business does; grounds the fit (suggest-* modes)."),
      company_id: z.string().optional().describe("Optional O-mega/Founden company id; pulls the real business brief to ground the fit."),
      purpose: z.enum(["website", "cold", "extra"]).optional().describe("What the domain is for (suggest-names / suggest-extensions): website (the site address), cold (a dedicated cold-email domain, kept apart from the site) or extra. Context the model weighs when judging fit; it sets no search options, which are yours to choose (search_options) from what the company needs."),
      search_options: z.record(z.string(), z.unknown()).optional().describe("Search options, only the fields you set (suggest-names / search-extensions / suggest-extensions): priorities (objective keys in priority order: total_length, annual_price, renewal_price, registration_total, semantic_fit, brandability, label_length), max_total_length and max_label_length (characters), max_annual_price, max_renewal_price and max_registration_total (USD), hacks (include, exclude or only) and allow_premium (boolean). A field you set wins over what the company_name brief asks for; null (or priorities: []) leaves that field to the brief; unknown keys are rejected. Options that do not apply to a mode are ignored there. The response echoes the effective options (search-extensions: search_options; suggest-names: search_plan.search_options)."),
      query: z.string().optional().describe("An exact name to check across extensions (search-extensions)."),
      domains: z.array(z.string()).optional().describe("Full domains to check, e.g. [\"brewhaven.com\"] (check-availability)."),
      tlds: z.array(z.string()).optional().describe("Extensions to price (pricing), to check the name across (search-extensions), or to restrict name ideas to (suggest-names)."),
      exact_extension: z.boolean().optional().default(false).describe("search-extensions: check ONLY the typed extension."),
      offset: z.number().optional().default(0).describe("search-extensions: pagination offset into the catalog."),
    },
  },
];
